CREATE TABLE USER (
  USER_ID        INT                   NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(42),
  LASTNAME  VARCHAR(42),
  BIRTH    DATE,
  PHONE     CHAR(12),
  EMAIL     VARCHAR(42),
  LOGIN     VARCHAR(42)           NOT NULL,
  PASSWORD  VARCHAR(42)           NOT NULL,
  CITY   VARCHAR(42)           NOT NULL,
  COUNTRY   VARCHAR(42)           NOT NULL,
  ADDRESS   VARCHAR(42)           NOT NULL,
  POSTCODE  VARCHAR(42)           NOT NULL,
  BANNED BOOLEAN DEFAULT FALSE,
  ROLE_ID INT                    NOT NULL,
  FOREIGN KEY (role_id) REFERENCES ROLE (role_id)
);
CREATE TABLE ROLE (
  role_id   INT PRIMARY KEY NOT NULL,
  name VARCHAR(30)
);

INSERT INTO role VALUES (1, 'USER');
INSERT INTO role VALUES (2, 'ADMINISTRATOR');


CREATE TABLE PRICE (
  PRICE_ID INT                   NOT NULL AUTO_INCREMENT,
  VALUE    DECIMAL(20, 4)        NOT NULL,
);

CREATE TABLE DATE (
  DATE_ID INT                   NOT NULL AUTO_INCREMENT,
  TIME    BIGINT                NOT NULL,
  DELETED BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE STATUS (
  STATUS_ID INT                    NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR_IGNORECASE(32) NOT NULL,
);

INSERT INTO status VALUES (1, 'paid');
INSERT INTO status VALUES (2, 'unpaid');
INSERT INTO status VALUES (3, 'delivery');
INSERT INTO status VALUES (4, 'delivered');
INSERT INTO status VALUES (5, 'canceled');

CREATE TABLE PRODUCT (
  PRODUCT_ID  INT           NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(128)  NOT NULL,
  CATEGORY_ID INT           NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  PRICE_ID    INT           NOT NULL,
  IMAGE_ID    INT           NOT NULL,
  IS_AVAILABLE BOOLEAN DEFAULT FALSE NOT NULL;
);
CREATE TABLE IMAGE (
  IMAGE_ID      INT                   NOT NULL AUTO_INCREMENT,
  IMAGENAME          VARCHAR(128)          NOT NULL,
  CONTENT_TYPE  VARCHAR(32)           NOT NULL,
  CONTENT       BLOB              NOT NULL,
  LAST_MODIFIED TIMESTAMP(0)          NOT NULL,
  DELETED       BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE CATEGORY (
  CATEGORY_ID INT                     NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR_IGNORECASE(128) NOT NULL,
);

CREATE TABLE PURCHASE (
  PURCHASE_ID BIGINT PRIMARY KEY    NOT NULL AUTO_INCREMENT,
  USER_ID     INT                   NOT NULL,
  PRICE_ID    INT                   NOT NULL,
  DATE_ID     INT                   NOT NULL,
  STATUS_ID   INT DEFAULT 1         NOT NULL,

  FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
  FOREIGN KEY (STATUS_ID) REFERENCES STATUS(STATUS_ID),
  FOREIGN KEY (PRICE_ID) REFERENCES PRICE(PRICE_ID),
);

CREATE TABLE PRODUCT_PURCHASE (
PRODUCT_PURCHASE_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
PURCHASE_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
AMOUNT INT NOT NULL,
FOREIGN KEY (PURCHASE_ID) references PURCHASE(PURCHASE_ID)
);
